name: Verifies PR are ready for merge

on:
  pull_request:
    branches:
      - main

jobs:
  verify-devcontainer:
    uses: project-origin/.github/.github/workflows/reusable-verify-devcontainer.yaml@f47fe5ea4b81d0d90f5a66898b090d148d8dcd60

  verify-code:
    uses: project-origin/.github/.github/workflows/reusable-verify-code.yaml@f47fe5ea4b81d0d90f5a66898b090d148d8dcd60

  verify-renovate:
    uses: project-origin/.github/.github/workflows/reusable-verify-renovate.yaml@f47fe5ea4b81d0d90f5a66898b090d148d8dcd60

  verify-build-nuget:
    uses: project-origin/.github/.github/workflows/reusable-build-nuget-package.yaml@f47fe5ea4b81d0d90f5a66898b090d148d8dcd60
    with:
      version: 0.0.1
      configuration: Release
      nuget_artifact: nuget-packages
      project: .
