name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyse:
    uses: project-origin/.github/.github/workflows/reusable-sonarcloud.yaml@3fa16fca8e3a41013342a13d9b71f280f12e750f
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
