name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyse:
    uses: project-origin/.github/.github/workflows/reusable-sonarcloud.yaml@f47fe5ea4b81d0d90f5a66898b090d148d8dcd60
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
